// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA940W90FhAzJ8rdsmWI9IGIBtnxOLoOlk',
    appId: '1:71371927533:web:5b5836cf90f32df2bb01e4',
    messagingSenderId: '71371927533',
    projectId: 'para-3bee8',
    authDomain: 'para-3bee8.firebaseapp.com',
    storageBucket: 'para-3bee8.appspot.com',
    measurementId: 'G-ZHGLHJM4RM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkb7UY4JuruRA6p5iefKOkhAvY3l4i6So',
    appId: '1:71371927533:android:cb161963472fbc91bb01e4',
    messagingSenderId: '71371927533',
    projectId: 'para-3bee8',
    storageBucket: 'para-3bee8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmL4OsU45jogJ8CV4rjAs6ADKLAOtCOsY',
    appId: '1:71371927533:ios:4492b42bd7614026bb01e4',
    messagingSenderId: '71371927533',
    projectId: 'para-3bee8',
    storageBucket: 'para-3bee8.appspot.com',
    iosBundleId: 'com.example.reddit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmL4OsU45jogJ8CV4rjAs6ADKLAOtCOsY',
    appId: '1:71371927533:ios:4492b42bd7614026bb01e4',
    messagingSenderId: '71371927533',
    projectId: 'para-3bee8',
    storageBucket: 'para-3bee8.appspot.com',
    iosBundleId: 'com.example.reddit',
  );
}
